// captchax/sdk/nextjs/src/app/CaptchaSlider.tsx
'use client';

import { useState, useRef, useCallback, useEffect } from 'react';

interface CaptchaSliderProps {
  onSuccess: (token: string) => void;
  onError?: (error: Error) => void;
  onClose?: () => void;
  scene?: string;
  serverUrl?: string;
  apiKey?: string;
  width?: number;
  height?: number;
}

interface SliderState {
  dragging: boolean;
  x: number;
  startX: number;
}

export function CaptchaSlider({
  onSuccess,
  onError,
  onClose,
  scene = 'default',
  serverUrl = 'https://api.captchax.com',
  apiKey = '',
  width = 300,
  height = 150
}: CaptchaSliderProps) {
  const [loading, setLoading] = useState(false);
  const [challenge, setChallenge] = useState<{
    backgroundImage?: string;
    sliderImage?: string;
    targetX?: number;
    targetY?: number;
  } | null>(null);
  const [sliderState, setSliderState] = useState<SliderState>({
    dragging: false,
    x: 0,
    startX: 0
  });
  const [error, setError] = useState<string | null>(null);
  
  const containerRef = useRef<HTMLDivElement>(null);
  const sliderRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    fetchChallenge();
  }, []);

  const fetchChallenge = async () => {
    if (!apiKey) {
      setError('API key is required');
      return;
    }

    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${serverUrl}/api/v1/captcha/slider`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          scene,
          apiKey,
          timestamp: Date.now()
        })
      });
      const data = await response.json();
      if (data.success) {
        setChallenge(data);
      } else {
        setError(data.error || 'Failed to load challenge');
      }
    } catch (err) {
      const error = err instanceof Error ? err : new Error('Failed to load challenge');
      setError(error.message);
      onError?.(error);
    } finally {
      setLoading(false);
    }
  };

  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    setSliderState(prev => ({
      ...prev,
      dragging: true,
      startX: e.clientX
    }));
  }, []);

  const handleTouchStart = useCallback((e: React.TouchEvent) => {
    const touch = e.touches[0];
    setSliderState(prev => ({
      ...prev,
      dragging: true,
      startX: touch.clientX
    }));
  }, []);

  useEffect(() => {
    if (!sliderState.dragging) return;

    const handleMouseMove = (e: MouseEvent) => {
      const deltaX = e.clientX - sliderState.startX;
      const clampedX = Math.max(0, Math.min(deltaX, width - 40));
      setSliderState(prev => ({ ...prev, x: clampedX }));
    };

    const handleTouchMove = (e: TouchEvent) => {
      const touch = e.touches[0];
      const deltaX = touch.clientX - sliderState.startX;
      const clampedX = Math.max(0, Math.min(deltaX, width - 40));
      setSliderState(prev => ({ ...prev, x: clampedX }));
    };

    const handleEnd = async () => {
      if (!sliderState.dragging) return;
      
      setLoading(true);
      try {
        const response = await fetch(`${serverUrl}/api/v1/captcha/slider/verify`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            scene,
            apiKey,
            offsetX: sliderState.x,
            timestamp: Date.now()
          })
        });
        const data = await response.json();
        
        if (data.success) {
          onSuccess(data.token);
        } else {
          setError(data.error || 'Verification failed');
          setSliderState({ dragging: false, x: 0, startX: 0 });
          fetchChallenge();
        }
      } catch (err) {
        const error = err instanceof Error ? err : new Error('Verification failed');
        onError?.(error);
        setError(error.message);
      } finally {
        setLoading(false);
        setSliderState(prev => ({ ...prev, dragging: false }));
      }
    };

    document.addEventListener('mousemove', handleMouseMove);
    document.addEventListener('mouseup', handleEnd);
    document.addEventListener('touchmove', handleTouchMove);
    document.addEventListener('touchend', handleEnd);

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleEnd);
      document.removeEventListener('touchmove', handleTouchMove);
      document.removeEventListener('touchend', handleEnd);
    };
  }, [sliderState.dragging, sliderState.startX, width, scene, apiKey, serverUrl, onSuccess, onError]);

  return (
    <div
      ref={containerRef}
      style={{
        width: `${width}px`,
        backgroundColor: '#f9fafb',
        borderRadius: '8px',
        padding: '16px',
        boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
      }}
    >
      <div
        style={{
          width: `${width}px`,
          height: `${height}px`,
          backgroundColor: '#e5e7eb',
          borderRadius: '6px',
          position: 'relative',
          overflow: 'hidden',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center'
        }}
      >
        {loading && <div style={{ color: '#6b7280' }}>加载中...</div>}
        {error && <div style={{ color: '#ef4444' }}>{error}</div>}
        {!loading && !error && challenge && (
          <>
            {challenge.backgroundImage && (
              <img
                src={challenge.backgroundImage}
                alt="background"
                style={{
                  width: '100%',
                  height: '100%',
                  objectFit: 'cover',
                  position: 'absolute'
                }}
              />
            )}
            <div
              style={{
                position: 'absolute',
                left: `${sliderState.x}px`,
                top: '50%',
                transform: 'translateY(-50%)',
                width: '40px',
                height: '40px',
                backgroundColor: 'white',
                borderRadius: '4px',
                boxShadow: '0 2px 4px rgba(0,0,0,0.2)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                cursor: sliderState.dragging ? 'grabbing' : 'grab'
              }}
              onMouseDown={handleMouseDown}
              onTouchStart={handleTouchStart}
              ref={sliderRef}
            >
              <span style={{ fontSize: '20px' }}>→</span>
            </div>
          </>
        )}
      </div>

      <div
        style={{
          marginTop: '12px',
          height: '4px',
          backgroundColor: '#d1d5db',
          borderRadius: '2px',
          overflow: 'hidden'
        }}
      >
        <div
          style={{
            height: '100%',
            width: `${(sliderState.x / (width - 40)) * 100}%`,
            backgroundColor: sliderState.dragging ? '#4F46E5' : '#d1d5db',
            transition: sliderState.dragging ? 'none' : 'width 0.2s ease'
          }}
        />
      </div>

      <p style={{ marginTop: '8px', fontSize: '12px', color: '#6b7280', textAlign: 'center' }}>
        {sliderState.dragging ? '拖动滑块完成验证' : '请拖动滑块到正确位置'}
      </p>

      {onClose && (
        <button
          onClick={onClose}
          style={{
            marginTop: '12px',
            width: '100%',
            padding: '8px',
            backgroundColor: 'white',
            border: '1px solid #d1d5db',
            borderRadius: '6px',
            cursor: 'pointer'
          }}
        >
          取消
        </button>
      )}
    </div>
  );
}

export default CaptchaSlider;

// captchax/sdk/vue/nuxt-module/src/runtime/components/CaptchaSlider.vue
<template>
  <div class="captcha-slider">
    <div class="captcha-slider__background" :style="backgroundStyle">
      <div 
        class="captcha-slider__target" 
        :style="targetStyle"
      ></div>
    </div>
    
    <div class="captcha-slider__track" ref="trackRef">
      <div 
        class="captcha-slider__thumb" 
        :style="thumbStyle"
        @mousedown="handleDragStart"
        @touchstart.passive="handleDragStart"
      >
        <svg class="captcha-slider__arrow" viewBox="0 0 24 24" fill="currentColor">
          <path d="M8.59 16.59L13.17 12 8.59 7.41 10 6l6 6-6 6-1.41-1.41z"/>
        </svg>
      </div>
    </div>
    
    <div class="captcha-slider__tips">
      <span v-if="!isVerified">{{ tips }}</span>
      <span v-else class="captcha-slider__success">验证成功</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useCaptchaState } from '../composables/useCaptchaState';

interface Props {
  targetImage?: string;
  sliderImage?: string;
}

const props = withDefaults(defineProps<Props>(), {
  targetImage: '',
  sliderImage: ''
});

const emit = defineEmits<{
  success: [token: string];
  error: [error: Error];
}>();

const { setLoading, setToken, setError, isLoading } = useCaptchaState();

const isDragging = ref(false);
const isVerified = ref(false);
const distance = ref(0);
const trackRef = ref<HTMLElement | null>(null);
const tips = ref('拖动滑块完成拼图');

const targetPosition = Math.floor(Math.random() * 40) + 30;

const backgroundStyle = computed(() => ({
  backgroundImage: props.targetImage ? `url(${props.targetImage})` : 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  backgroundSize: 'cover'
}));

const targetStyle = computed(() => ({
  left: `${targetPosition}%`,
  top: `${Math.floor(Math.random() * 40) + 10}%`
}));

const thumbStyle = computed(() => ({
  transform: `translateX(${distance.value}px)`
}));

let startX = 0;

const handleDragStart = (e: MouseEvent | TouchEvent) => {
  if (isVerified.value || isLoading.value) return;
  
  isDragging.value = true;
  startX = 'touches' in e ? e.touches[0].clientX : e.clientX;
  
  document.addEventListener('mousemove', handleDragMove);
  document.addEventListener('mouseup', handleDragEnd);
  document.addEventListener('touchmove', handleDragMove);
  document.addEventListener('touchend', handleDragEnd);
};

const handleDragMove = (e: MouseEvent | TouchEvent) => {
  if (!isDragging.value) return;
  
  const clientX = 'touches' in e ? e.touches[0].clientX : e.clientX;
  const deltaX = clientX - startX;
  
  if (trackRef.value) {
    const maxDistance = trackRef.value.offsetWidth - 40;
    distance.value = Math.max(0, Math.min(deltaX, maxDistance));
  }
};

const handleDragEnd = async () => {
  if (!isDragging.value) return;
  
  isDragging.value = false;
  
  document.removeEventListener('mousemove', handleDragMove);
  document.removeEventListener('mouseup', handleDragEnd);
  document.removeEventListener('touchmove', handleDragMove);
  document.removeEventListener('touchend', handleDragEnd);
  
  const threshold = targetPosition * (trackRef.value?.offsetWidth / 100);
  const tolerance = 10;
  
  if (Math.abs(distance.value - threshold) <= tolerance) {
    isVerified.value = true;
    tips.value = '';
    
    try {
      const token = `slider_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
      setToken(token);
      setLoading(false);
      emit('success', token);
    } catch (error) {
      setError(error as Error);
      emit('error', error as Error);
    }
  } else {
    distance.value = 0;
    tips.value = '验证失败，请重试';
    emit('error', new Error('Verification failed'));
  }
};
</script>

<style scoped>
.captcha-slider {
  width: 300px;
  user-select: none;
}

.captcha-slider__background {
  position: relative;
  width: 100%;
  height: 150px;
  border-radius: 4px;
  overflow: hidden;
}

.captcha-slider__target {
  position: absolute;
  width: 40px;
  height: 40px;
  background: rgba(255, 255, 255, 0.9);
  border-radius: 4px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
  display: flex;
  align-items: center;
  justify-content: center;
}

.captcha-slider__track {
  position: relative;
  width: 100%;
  height: 40px;
  background: #f0f0f0;
  border-radius: 20px;
  margin-top: 16px;
  overflow: hidden;
}

.captcha-slider__thumb {
  position: absolute;
  left: 0;
  top: 0;
  width: 40px;
  height: 40px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 50%;
  cursor: grab;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  transition: transform 0.1s ease;
}

.captcha-slider__thumb:hover {
  transform: scale(1.05);
}

.captcha-slider__thumb:active {
  cursor: grabbing;
}

.captcha-slider__arrow {
  width: 20px;
  height: 20px;
  color: white;
}

.captcha-slider__tips {
  text-align: center;
  margin-top: 12px;
  font-size: 14px;
  color: #666;
}

.captcha-slider__success {
  color: #52c41a;
}
</style>
